name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Install depedencies
      run: go get honnef.co/go/tools/cmd/staticcheck

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -convermode=atomic

    - name: Staticheck
      run: statickcheck ./...
      
    - name: Send coverage
      run: bash <(curl -s https://codecov.io/bash)
